name = "csp-headers"
main = "index.ts"
compatibility_date = "2024-03-01"
account_id = "6e52900b964c300ce471624d4ee8fc4e"

routes = [
  { pattern = "portalraregroove.com/*", zone_name = "portalraregroove.com" }
]
